import streamlit as st
import pandas as pd
import plotly.express as px
from datetime import datetime, date
import os
import hashlib
import re

# ---------------------------------------------------------
# STREAMLIT PAGE CONFIG & CUSTOM STYLING
# ---------------------------------------------------------
st.set_page_config(
    page_title="Federal TVET Executive CMMS v10.2", 
    layout="wide", 
    page_icon="🛡️"
)

st.markdown("""
<style>
    .stApp { background-color: #F8FAFC; }
    div[data-testid="stMetricValue"] { font-size: 1.6rem !important; }
    .top-bar-title {
        background-color: #0F172A;
        color: white;
        padding: 12px 20px;
        border-radius: 8px;
        margin-bottom: 15px;
        text-align: center;
        border-bottom: 4px solid #3B82F6;
    }
    @media (max-width: 768px) {
        .stApp { padding: 5px !important; }
    }
</style>
""", unsafe_allow_html=True)

# ---------------------------------------------------------
# SECURITY HELPER FUNCTIONS
# ---------------------------------------------------------
def hash_password(password: str) -> str:
    """Hashes passwords using SHA-256 algorithm with salt."""
    salt = "TVET_CMMS_SECURE_SALT_2026"
    return hashlib.sha256((password + salt).encode('utf-8')).hexdigest()

def validate_password_strength(password: str) -> tuple[bool, str]:
    """Enforces strict password rules."""
    if len(password) < 8:
        return False, "የይለፍ ቃል ቢያንስ 8 ቁምፊዎች (Characters) ሊኖረው ይገባል!"
    if not re.search(r"\d", password):
        return False, "የይለፍ ቃል ቢያንስ አንድ ቁጥር (0-9) ማካተት አለበት!"
    if not re.search(r"[A-Z]", password):
        return False, "የይለፍ ቃል ቢያንስ አንድ ትልቅ እንግሊዝኛ ሌተር (A-Z) ማካተት አለበት!"
    if not re.search(r"[!@#$%^&*(),.?\":{}|<>]", password):
        return False, "የይለፍ ቃል ቢያንስ አንድ ልዩ ምልክት (@, #, $, %, ...) ማካተት አለበት!"
    return True, "Strong"

def sanitize_input(text: str) -> str:
    """Sanitizes strings to prevent XSS / Code Injection attacks."""
    if not isinstance(text, str):
        return text
    clean_text = re.sub(r'<[^>]*>', '', text)
    clean_text = clean_text.replace('"', '&quot;').replace("'", "&#39;")
    return clean_text.strip()

# File Paths
USER_FILE = "tvet_users.csv"
ANNUAL_PLAN_FILE = "tvet_annual_plan.csv"
REPORT_HISTORY_FILE = "tvet_report_history.csv"

# Safe Data Loader
def load_data(file_path, columns):
    if not os.path.exists(file_path):
        df = pd.DataFrame(columns=columns)
        df.to_csv(file_path, index=False)
        return df
    try:
        df = pd.read_csv(file_path)
        for col in columns:
            if col not in df.columns:
                df[col] = "N/A"
        return df
    except Exception:
        df = pd.DataFrame(columns=columns)
        df.to_csv(file_path, index=False)
        return df

def save_data(df, file_path):
    df.to_csv(file_path, index=False)

# File Columns Definitions
user_cols = ["Full Name", "Department", "Job Title / Responsibility", "Role Privilege", "Username", "Password", "Registered Date"]
plan_cols = [
    "Plan ID", "Department", "Work Category", "Task Title", "Location", "Quarter", 
    "Execution Mode", "Contractor Name", "Contract Ref No", "Contract Terms",
    "Start Date", "End Date", "Priority Level", "Assigned Team", "Budget (ETB)", "Progress (%)", "Status"
]
report_cols = ["Report ID", "Report Title", "Timeframe", "Report Category", "Generated By", "Generated Date", "Total Tasks Count"]

# Load System Data
users_df = load_data(USER_FILE, user_cols)
plan_df = load_data(ANNUAL_PLAN_FILE, plan_cols)
reports_df = load_data(REPORT_HISTORY_FILE, report_cols)

# Ensure Default System Admin Account Exists
if users_df.empty or "admin" not in users_df["Username"].values:
    default_admin = pd.DataFrame([[
        "System Administrator", 
        "Engineering Exec", 
        "System Management", 
        "System Admin (Full Access)", 
        "admin", 
        hash_password("Admin@1234"),
        datetime.now().strftime("%Y-%m-%d")
    ]], columns=user_cols)
    users_df = pd.concat([users_df, default_admin], ignore_index=True)
    save_data(users_df, USER_FILE)

# Priority Sorting Engine
def process_and_sort_plans(df):
    if df.empty:
        return df
    df["Progress (%)"] = pd.to_numeric(df["Progress (%)"], errors='coerce').fillna(0).astype(int)
    df["Budget (ETB)"] = pd.to_numeric(df["Budget (ETB)"], errors='coerce').fillna(0.0)
    priority_weights = {"🔴 High / Emergency": 3, "🟡 Medium": 2, "🟢 Low": 1}
    df["Priority_Score"] = df["Priority Level"].map(priority_weights).fillna(1)
    df["Temp_End_Date"] = pd.to_datetime(df["End Date"], errors='coerce')
    df = df.sort_values(
        by=["Status", "Priority_Score", "Temp_End_Date"], 
        ascending=[True, False, True]
    ).drop(columns=["Priority_Score", "Temp_End_Date"])
    return df

plan_df = process_and_sort_plans(plan_df)

# ---------------------------------------------------------
# AUTHENTICATION & LOGIN
# ---------------------------------------------------------
if 'logged_in' not in st.session_state:
    st.session_state.logged_in = False
    st.session_state.user_info = None
if 'failed_attempts' not in st.session_state:
    st.session_state.failed_attempts = 0

def login():
    st.title("🛡️ Federal TVET - CMMS v10.2 Access Portal")
    st.caption("🔒 የተጠበቀ የሲስተም መግቢያ ገጽ - እባክዎን ህጋዊ የሆነ የመግቢያ መረጃዎን ያስገቡ")
    
    col1, col2, col3 = st.columns([1, 2, 1])
    with col2:
        st.markdown("### 🔑 የመግቢያ ፎርም")
        
        if st.session_state.failed_attempts >= 3:
            st.error("⛔ በተደጋጋሚ የተሳሳተ የይለፍ ቃል በመሞከርዎ አካውንቱ ተቆልፏል! እባክዎን ገጹን Refresh አድርገው እንደገና ይሞክሩ።")
            st.stop()
            
        input_user = sanitize_input(st.text_input("የተጠቃሚ ስም (Username):"))
        input_pass = st.text_input("የመተላለፊያ ቃል (Password):", type="password")
        
        if st.button("ወደ ሲስተሙ ግባ (Secure Login)", use_container_width=True):
            hashed_input_pass = hash_password(input_pass.strip())
            
            user_match = users_df[
                (users_df["Username"] == input_user.strip()) & 
                ((users_df["Password"] == hashed_input_pass) | (users_df["Password"] == input_pass.strip()))
            ]
            
            if not user_match.empty:
                st.session_state.logged_in = True
                st.session_state.user_info = user_match.iloc[0].to_dict()
                st.session_state.failed_attempts = 0
                st.success(f"እንኳን በደህና መጡ {st.session_state.user_info['Full Name']}!")
                st.rerun()
            else:
                st.session_state.failed_attempts += 1
                remaining = 3 - st.session_state.failed_attempts
                st.error(f"⛔ የተሳሳተ የተጠቃሚ ስም ወይም የይለፍ ቃል! (የቀረዎት ሙከራ፦ {remaining})")

if not st.session_state.logged_in:
    login()
    st.stop()

user = st.session_state.user_info
role = user["Role Privilege"]
can_edit = "Editor" in role or "Admin" in role

# ---------------------------------------------------------
# 🔝 TOP NAVBAR (MAIN NAVIGATION)
# ---------------------------------------------------------
st.markdown("<div class='top-bar-title'><h2>🏗️ FEDERAL TVET CMMS - SECURED SYSTEM</h2></div>", unsafe_allow_html=True)

top_cols = st.columns([1, 1, 1, 1])

if 'active_top_tab' not in st.session_state:
    st.session_state.active_top_tab = "📊 Dashboard & Overview"

with top_cols[0]:
    if st.button("📊 Dashboard & Overview", use_container_width=True):
        st.session_state.active_top_tab = "📊 Dashboard & Overview"
        st.rerun()

with top_cols[1]:
    if st.button("📋 Task Management", use_container_width=True):
        st.session_state.active_top_tab = "📋 Task Management"
        st.rerun()

with top_cols[2]:
    if st.button("📄 Advanced Reports", use_container_width=True):
        st.session_state.active_top_tab = "📄 Advanced Reports"
        st.rerun()

with top_cols[3]:
    if st.button("👥 Admin & Settings", use_container_width=True):
        st.session_state.active_top_tab = "👥 Admin & Settings"
        st.rerun()

st.markdown("---")

# ---------------------------------------------------------
# 👈 DYNAMIC SIDEBAR
# ---------------------------------------------------------
st.sidebar.title(f"👤 {user['Full Name']}")
st.sidebar.info(f"**ክፍል:** {user['Department']}\n\n**ስልጣን:** {role}")

if st.sidebar.button("🚪 ውጣ (Secure Logout)"):
    st.session_state.logged_in = False
    st.session_state.user_info = None
    st.rerun()

st.sidebar.markdown("---")
st.sidebar.subheader("📂 Sub-Menu / ንዑስ ክፍሎች")

main_tab = st.session_state.active_top_tab

if main_tab == "📊 Dashboard & Overview":
    sub_page = st.sidebar.radio("ምርጫዎች", ["የስራዎች አጠቃላይ ዳሽቦርድ (Executive Dashboard)"])

elif main_tab == "📋 Task Management":
    sub_menu_options = ["የቅድሚያ ቅደም ተከተል የስራዎች ሰንጠረዥ"]
    if can_edit:
        sub_menu_options.append("➕ አዲስ ስራ በእጅ መመዝገቢያ")
        sub_menu_options.append("🛠️ የፕሮግረስ ማስተካከያ (Progress Update)")
    sub_page = st.sidebar.radio("ምርጫዎች", sub_menu_options)

elif main_tab == "📄 Advanced Reports":
    sub_page = st.sidebar.radio("ምርጫዎች", ["📊 አዲስ ሪፖርት ማውጫ (Report Generator)", "💾 የቆዩ የተቀመጡ ሪፖርቶች (Report History)"])

elif main_tab == "👥 Admin & Settings":
    admin_menu = []
    if "Admin" in role:
        admin_menu.append("👥 User Management & Privileges")
    admin_menu.append("🔒 የየአካውንት መረጃ እና የይለፍ ቃል መቀየሪያ")
    sub_page = st.sidebar.radio("ምርጫዎች", admin_menu)

# ---------------------------------------------------------
# 1. EXECUTIVE DASHBOARD (FULL OVERVIEW WITH CHARTS)
# ---------------------------------------------------------
if main_tab == "📊 Dashboard & Overview":
    st.title("📊 የምህንድስና እና ጥገና ስራ አስፈፃሚ - Executive Dashboard")
    st.caption("የሁሉም ክፍሎች (ሲቪል/ኮንስትራክሽን፣ ኤሌክትሪክ፣ ሳኒተሪ) የአዲስና የጥገና ስራዎች አጠቃላይ አፈፃፀም መከታተያ")

    # Filters
    f1, f2, f3 = st.columns(3)
    with f1:
        sel_dept = st.selectbox("የስራ ዘርፍ (Department):", ["ሁሉንም አሳይ (All)", "Construction", "Electrical", "Sanitary"])
    with f2:
        sel_qtr = st.selectbox("የጊዜ ክፍተት (Quarter):", ["ሁሉንም አሳይ (All)", "Q1", "Q2", "Q3", "Q4"])
    with f3:
        sel_mode = st.selectbox("የአሰራር ሁኔታ (Execution Mode):", ["ሁሉንም አሳይ (All)", "In-House (በውስጥ አቅም)", "Outsourced / Contract (በጨረታ)"])

    filtered_p = plan_df.copy()
    if sel_dept != "ሁሉንም አሳይ (All)":
        filtered_p = filtered_p[filtered_p["Department"] == sel_dept]
    if sel_qtr != "ሁሉንም አሳይ (All)":
        filtered_p = filtered_p[filtered_p["Quarter"] == sel_qtr]
    if sel_mode != "ሁሉንም አሳይ (All)":
        filtered_p = filtered_p[filtered_p["Execution Mode"] == sel_mode]

    avg_progress = filtered_p["Progress (%)"].mean() if not filtered_p.empty else 0.0

    st.markdown("---")
    # Metric KPI Cards
    k1, k2, k3, k4, k5, k6 = st.columns(6)
    k1.metric("ጠቅላላ የታቀዱ", len(filtered_p))
    k2.metric("የተጠናቀቁ (100%)", len(filtered_p[filtered_p["Status"] == "Completed"]) if not filtered_p.empty else 0)
    k3.metric("በሂደት ላይ (1-99%)", len(filtered_p[filtered_p["Status"] == "In Progress"]) if not filtered_p.empty else 0)
    k4.metric("አስቸኳይ ስራዎች", len(filtered_p[filtered_p["Priority Level"].str.contains("High", na=False)]) if not filtered_p.empty else 0)
    k5.metric("አማካኝ አፈፃፀም", f"{avg_progress:.1f}%")
    k6.metric("ጠቅላላ በጀት", f"{filtered_p['Budget (ETB)'].sum():,.0f} ETB" if not filtered_p.empty else "0 ETB")

    st.markdown("---")
    
    # CHARTS SECTION
    if not filtered_p.empty:
        c1, c2 = st.columns(2)
        
        with c1:
            st.subheader("📌 የስራዎች ብዛት በዘርፍ እና በስራ አይነት")
            fig_type = px.histogram(
                filtered_p, 
                x="Department", 
                color="Work Category", 
                barmode="group",
                color_discrete_sequence=["#3B82F6", "#10B981"],
                text_auto=True
            )
            fig_type.update_layout(xaxis_title="የስራ ዘርፍ", yaxis_title="የስራዎች ብዛት", legend_title="የስራ አይነት")
            st.plotly_chart(fig_type, use_container_width=True)

        with c2:
            st.subheader("💰 የበጀት ክፍፍል በየጊዜ ክፍተቱ (Quarter)")
            fig_budget = px.pie(
                filtered_p, 
                names="Quarter", 
                values="Budget (ETB)", 
                hole=0.4,
                color_discrete_sequence=px.colors.qualitative.Pastel
            )
            st.plotly_chart(fig_budget, use_container_width=True)

        st.markdown("---")
        st.subheader("📈 የእያንዳንዱ ስራ አፈፃፀም፣ የሰራው አይነት እና ኃላፊነት የወሰደው ሰው/ቡድን")
        
        # Individual Task Progress Chart
        fig_progress = px.bar(
            filtered_p,
            y="Task Title",
            x="Progress (%)",
            color="Department",
            hover_data=["Work Category", "Assigned Team", "Location", "Priority Level"],
            orientation="h",
            text="Progress (%)",
            color_discrete_map={"Construction": "#10B981", "Electrical": "#EF4444", "Sanitary": "#3B82F6"}
        )
        fig_progress.update_layout(
            yaxis={'categoryorder':'total ascending'},
            yaxis_title="የስራው መግለጫ / አርእስት",
            xaxis_title="የተሰራው አፈፃፀም (%)",
            xaxis=dict(range=[0, 100])
        )
        st.plotly_chart(fig_progress, use_container_width=True)

        st.markdown("### 📋 የአሁኑ የስራዎች ዝርዝር መረጃ ሰንጠረዥ")
        st.dataframe(
            filtered_p[["Plan ID", "Department", "Work Category", "Task Title", "Location", "Assigned Team", "Priority Level", "Progress (%)", "Status"]], 
            use_container_width=True
        )
    else:
        st.info("ℹ️ በተመረጠው ማጣሪያ መሰረት ምንም የተመዘገበ ስራ የለም።")

# ---------------------------------------------------------
# 2. TASK MANAGEMENT
# ---------------------------------------------------------
elif main_tab == "📋 Task Management":
    if sub_page == "የቅድሚያ ቅደም ተከተል የስራዎች ሰንጠረዥ":
        st.title("📋 አውቶማቲክ ቅድሚያ የተሰጣቸው የስራዎች ሰንጠረዥ")
        st.dataframe(plan_df, use_container_width=True)

    elif sub_page == "➕ አዲስ ስራ በእጅ መመዝገቢያ":
        st.title("➕ አዲስ ስራ በእጅ መመዝገቢያ")
        with st.form("manual_task_form"):
            st.subheader("📝 የስራው መረጃ ይሙሉ")
            c1, c2 = st.columns(2)
            with c1:
                t_dept = st.selectbox("የስራ ዘርፍ", ["Construction", "Electrical", "Sanitary"])
                t_cat = st.selectbox("የስራ አይነት", ["New Project (አዲስ ስራ)", "Maintenance (የጥገና ስራ)"])
                t_title = sanitize_input(st.text_input("የስራው መግለጫ / አርእስት*"))
                t_loc = sanitize_input(st.text_input("የሚሰራበት ቦታ / ህንፃ*"))
                t_mode = st.selectbox("የአሰራር ሁኔታ*", ["In-House (በውስጥ አቅም)", "Outsourced / Contract (በጨረታ)"])
                t_team = sanitize_input(st.text_input("ኃላፊነት የተሰጠው ቡድን/ባለሙያ*"))
            
            with c2:
                t_qtr = st.selectbox("Quarter", ["Q1", "Q2", "Q3", "Q4"])
                t_start = st.date_input("Start Date", value=date.today())
                t_end = st.date_input("End Date", value=date.today())
                t_prio = st.selectbox("የአስቸኳይነት ደረጃ*", ["🔴 High / Emergency", "🟡 Medium", "🟢 Low"])
                t_budget = st.number_input("የተመደበ በጀት (ETB)", min_value=0.0, step=1000.0)

            c_name = sanitize_input(st.text_input("የኮንትራክተር ስም (ካለ)", value="N/A"))
            c_ref = sanitize_input(st.text_input("የውል ስምምነት ቁጥር (ካለ)", value="N/A"))
            c_terms = sanitize_input(st.text_area("የውል አስፈላጊ ሁኔታዎች", value="N/A"))

            if st.form_submit_button("💾 ስራውን መዝግብ"):
                if t_title and t_loc:
                    new_id = f"PLAN-{len(plan_df) + 101}"
                    cat_clean = "New Project" if "New" in t_cat else "Maintenance"
                    
                    new_task_row = pd.DataFrame([[
                        new_id, t_dept, cat_clean, t_title, t_loc, t_qtr, 
                        t_mode, c_name, c_ref, c_terms,
                        str(t_start), str(t_end), t_prio, t_team, t_budget, 0, "Open"
                    ]], columns=plan_cols)
                    
                    plan_df = pd.concat([plan_df, new_task_row], ignore_index=True)
                    plan_df = process_and_sort_plans(plan_df)
                    save_data(plan_df, ANNUAL_PLAN_FILE)
                    st.success(f"✅ ስራው በስኬት ተመዝግቧል! ID: `{new_id}`")
                    st.rerun()

    elif sub_page == "🛠️ የፕሮግረስ ማስተካከያ (Progress Update)":
        st.title("🛠️ የሥራ ፕሮግረስ ማስተካከያ")
        if not plan_df.empty:
            sel_p = st.selectbox("የሚሰሩትን ስራ ይምረጡ:", plan_df["Plan ID"].dropna().tolist())
            p_data = plan_df[plan_df["Plan ID"] == sel_p].iloc[0]
            curr_prog = int(p_data.get("Progress (%)", 0))
            new_p = st.slider("አዲሱን የሥራ ፕሮግረስ (%) ይምረጡ:", min_value=0, max_value=100, value=curr_prog)
            
            auto_st = "Open" if new_p == 0 else ("In Progress" if new_p < 100 else "Completed")
            if st.button("ፕሮግረስ አዘምን"):
                plan_df.loc[plan_df["Plan ID"] == sel_p, "Progress (%)"] = new_p
                plan_df.loc[plan_df["Plan ID"] == sel_p, "Status"] = auto_st
                plan_df = process_and_sort_plans(plan_df)
                save_data(plan_df, ANNUAL_PLAN_FILE)
                st.success("✅ ፕሮግረሱ ተዘምኗል!")
                st.rerun()

# ---------------------------------------------------------
# 3. ADVANCED REPORTS
# ---------------------------------------------------------
elif main_tab == "📄 Advanced Reports":
    if sub_page == "📊 አዲስ ሪፖርት ማውጫ (Report Generator)":
        st.title("📄 የላቀ የሪፖርት ማውጫ")
        report_timeframe = st.selectbox("🗓️ የሪፖርት የጊዜ ርዝማኔ:", ["ሳምንታዊ (Weekly)", "ወርሃዊ (Monthly)", "የ3 ወር (Quarterly)", "የ6 ወር (Half-Year)", "የ9 ወር", "የዓመት (Annual)"])
        report_category = st.selectbox("🎯 የሪፖርት ዓይነት:", ["አጠቃላይ ሪፖርት", "በኮንትራክተር የተሰጡ", "በውስጥ አቅም የተሰሩ", "ኮንስትራክሽን", "ኤሌክትሪክ", "ሳኒተሪ"])
        
        st.dataframe(plan_df, use_container_width=True)
        if st.button("💾 ሪፖርቱን በሲስተሙ ታሪክ ውስጥ መዝግብ"):
            rep_id = f"REP-{len(reports_df) + 101}"
            new_rep_row = pd.DataFrame([[rep_id, report_category, report_timeframe, report_category, user["Full Name"], datetime.now().strftime("%Y-%m-%d %H:%M"), len(plan_df)]], columns=report_cols)
            reports_df = pd.concat([reports_df, new_rep_row], ignore_index=True)
            save_data(reports_df, REPORT_HISTORY_FILE)
            st.success("✅ ሪፖርቱ ተመዝግቧል!")

    elif sub_page == "💾 የቆዩ የተቀመጡ ሪፖርቶች (Report History)":
        st.title("💾 የተቀመጡ የቆዩ ሪፖርቶች ታሪክ")
        st.dataframe(reports_df, use_container_width=True)

# ---------------------------------------------------------
# 4. ADMIN & SETTINGS (USER MGMT & PASSWORD CHANGE)
# ---------------------------------------------------------
elif main_tab == "👥 Admin & Settings":
    if sub_page == "👥 User Management & Privileges":
        st.title("👥 የተጠቃሚዎች ምዝገባ እና የደህንነት መቆጣጠሪያ")
        
        with st.form("register_secure_user"):
            st.subheader("➕ አዲስ ተጠቃሚ በደህንነት ደንብ መመዝገቢያ")
            f_name = sanitize_input(st.text_input("ሙሉ ስም"))
            u_dept = st.selectbox("የሥራ ክፍል", ["Engineering Exec", "Construction Department", "Electrical Department", "Sanitary Department"])
            j_title = sanitize_input(st.text_area("የሥራ ድርሻ"))
            u_role = st.selectbox("የስልጣን ደረጃ", ["Viewer (ማየት ብቻ የሚችል)", "Editor & Reporter (ኤዲት ማድረግ የሚችል)", "System Admin (Full Control)"])
            u_name = sanitize_input(st.text_input("Username"))
            u_pass = st.text_input("Password (ቢያንስ 8 ቁምፊዎች፣ ቁጥር፣ ትልቅ ሌተር እና ልዩ ምልክት ያካተተ)*", type="password")
            
            if st.form_submit_button("🔒 ተጠቃሚውን መዝግብ"):
                is_valid, msg = validate_password_strength(u_pass)
                if not is_valid:
                    st.error(f"⛔ የደህንነት ስጋት፦ {msg}")
                elif u_name in users_df["Username"].values:
                    st.error("⛔ ይህ Username ቀደም ሲል ተይዟል! እባክዎን ሌላ ይምረጡ።")
                elif f_name and u_name and u_pass:
                    secure_pass = hash_password(u_pass)
                    new_u = pd.DataFrame([[f_name, u_dept, j_title, u_role, u_name, secure_pass, datetime.now().strftime("%Y-%m-%d")]], columns=user_cols)
                    users_df = pd.concat([users_df, new_u], ignore_index=True)
                    save_data(users_df, USER_FILE)
                    st.success(f"✅ ተጠቃሚ {f_name} በከፍተኛ ደህንነት ተመዝግቧል!")
                    st.rerun()

        st.markdown("---")
        st.subheader("የተመዘገቡ ተጠቃሚዎች ዝርዝር")
        st.dataframe(users_df.drop(columns=["Password"]), use_container_width=True)

    elif sub_page == "🔒 የየአካውንት መረጃ እና የይለፍ ቃል መቀየሪያ":
        st.title("🔒 የየአካውንት መረጃ እና የይለፍ ቃል መቀየሪያ")
        
        st.subheader("👤 የእርስዎን መረጃ")
        st.write(f"**ሙሉ ስም:** {user['Full Name']}")
        st.write(f"**የስራ ክፍል:** {user['Department']}")
        st.write(f"**የተጠቃሚ ስም (Username):** `{user['Username']}`")
        st.write(f"**የስልጣን ደረጃ:** {user['Role Privilege']}")
        
        st.markdown("---")
        st.subheader("🔑 የይለፍ ቃል መቀየሪያ (Change Password)")
        
        with st.form("change_password_form"):
            curr_pass = st.text_input("የአሁኑ የይለፍ ቃል (Current Password)*", type="password")
            new_pass = st.text_input("አዲስ የይለፍ ቃል (New Password)*", type="password")
            confirm_pass = st.text_input("አዲሱን የይለፍ ቃል ድገሙት (Confirm New Password)*", type="password")
            
            if st.form_submit_button("🔄 የይለፍ ቃሌን ቀይር"):
                hashed_curr_pass = hash_password(curr_pass.strip())
                
                # Check current password match
                if user["Password"] != hashed_curr_pass and user["Password"] != curr_pass.strip():
                    st.error("⛔ ያስገቡት የአሁኑ የይለፍ ቃል የተሳሳተ ነው!")
                elif new_pass != confirm_pass:
                    st.error("⛔ አዲሱ የይለፍ ቃል እና የማረጋገጫ የይለፍ ቃሉ አይመሳሰሉም!")
                else:
                    is_valid, msg = validate_password_strength(new_pass)
                    if not is_valid:
                        st.error(f"⛔ የደህንነት ስጋት፦ {msg}")
                    else:
                        hashed_new_pass = hash_password(new_pass)
                        users_df.loc[users_df["Username"] == user["Username"], "Password"] = hashed_new_pass
                        save_data(users_df, USER_FILE)
                        st.session_state.user_info["Password"] = hashed_new_pass
                        st.success("✅ የይለፍ ቃልዎ በስኬት ተቀይሯል!")