import streamlit as st
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from datetime import datetime, date, timedelta
import os
import hashlib
import re

# ---------------------------------------------------------
# STREAMLIT PAGE CONFIG & CUSTOM STYLING (v13.0 UI Engine)
# ---------------------------------------------------------
st.set_page_config(
    page_title="Federal TVET CMMS & Enterprise Suite v13.0", 
    layout="wide", 
    page_icon="🛡️"
)

st.markdown("""
<style>
    .stApp { background-color: #F8FAFC; }
    div[data-testid="stMetricValue"] { font-size: 1.5rem !important; }
    .top-bar-title {
        background-color: #0F172A;
        color: white;
        padding: 14px 20px;
        border-radius: 10px;
        margin-bottom: 15px;
        text-align: center;
        border-bottom: 4px solid #3B82F6;
        box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1);
    }
    .stButton > button {
        width: 100%;
        border-radius: 8px;
        font-weight: 600;
    }
</style>
""", unsafe_allow_html=True)

# ---------------------------------------------------------
# HELPER FUNCTIONS, SECURITY & SAFE SECRETS HANDLING
# ---------------------------------------------------------
def hash_password(password: str) -> str:
    salt = "TVET_CMMS_ENTERPRISE_SALT_2026"
    return hashlib.sha256((password + salt).encode('utf-8')).hexdigest()

def validate_password_strength(password: str) -> tuple[bool, str]:
    if len(password) < 8:
        return False, "የይለፍ ቃል ቢያንስ 8 ቁምፊዎች ሊኖረው ይገባል!"
    if not re.search(r"\d", password):
        return False, "የይለፍ ቃል ቢያንስ አንድ ቁጥር (0-9) ማካተት አለበት!"
    if not re.search(r"[A-Z]", password):
        return False, "የይለፍ ቃል ቢያንስ አንድ ትልቅ እንግሊዝኛ ሌተር (A-Z) ማካተት አለበት!"
    if not re.search(r"[!@#$%^&*(),.?\":{}|<>]", password):
        return False, "የይለፍ ቃል ቢያንስ አንድ ልዩ ምልክት (@, #, $, %, ...) ማካተት አለበት!"
    return True, "Strong"

def sanitize_input(text: str) -> str:
    if not isinstance(text, str):
        return text
    clean_text = re.sub(r'<[^>]*>', '', text)
    return clean_text.replace('"', '&quot;').replace("'", "&#39;").strip()

# Safe Secrets Configuration (Prevents StreamlitSecretNotFoundError)
try:
    GEMINI_API_KEY = st.secrets.get("GEMINI_API_KEY", "YOUR_GEMINI_API_KEY_HERE")
except Exception:
    GEMINI_API_KEY = "YOUR_GEMINI_API_KEY_HERE"

# ---------------------------------------------------------
# DATA FILES & SCHEMAS
# ---------------------------------------------------------
USER_FILE = "tvet_users.csv"
ANNUAL_PLAN_FILE = "tvet_annual_plan.csv"
ASSETS_FILE = "tvet_asset_register.csv"
INVENTORY_FILE = "tvet_inventory.csv"
PREVENTIVE_FILE = "tvet_preventive_maint.csv"
CORRECTIVE_FILE = "tvet_corrective_maint.csv"
REPORT_HISTORY_FILE = "tvet_report_history.csv"

def load_data(file_path, columns):
    if not os.path.exists(file_path):
        df = pd.DataFrame(columns=columns)
        df.to_csv(file_path, index=False)
        return df
    try:
        df = pd.read_csv(file_path)
        for col in columns:
            if col not in df.columns:
                df[col] = "N/A"
        return df
    except Exception:
        df = pd.DataFrame(columns=columns)
        df.to_csv(file_path, index=False)
        return df

def save_data(df, file_path):
    df.to_csv(file_path, index=False)

user_cols = ["Full Name", "Department", "Job Title / Responsibility", "Role Privilege", "Username", "Password", "Registered Date"]
plan_cols = ["Plan ID", "Department", "Work Category", "Task Title", "Location", "Quarter", "Execution Mode", "Contractor Name", "Contract Ref No", "Contract Terms", "Start Date", "End Date", "Priority Level", "Assigned Team", "Budget (ETB)", "Progress (%)", "Status"]
asset_cols = ["Asset ID", "Asset Name", "Category", "Department", "Location", "Purchase Date", "Cost (ETB)", "Condition", "Status", "QR Code Data"]
inventory_cols = ["Item Code", "Item Name", "Category", "Quantity In Stock", "Min Reorder Level", "Unit Cost (ETB)", "Total Value (ETB)", "Storage Bin"]
preventive_cols = ["PM ID", "Asset ID / Title", "Frequency", "Assigned Technician", "Last Service Date", "Next Scheduled Date", "Status"]
corrective_cols = ["Work Order ID", "Asset / Location", "Issue Description", "Reported By", "Reported Date", "Priority", "Technician Assigned", "Status"]
report_cols = ["Report ID", "Report Title", "Timeframe", "Department Filter", "Module Category", "Generated By", "Generated Date", "Total Records"]

users_df = load_data(USER_FILE, user_cols)
plan_df = load_data(ANNUAL_PLAN_FILE, plan_cols)
assets_df = load_data(ASSETS_FILE, asset_cols)
inventory_df = load_data(INVENTORY_FILE, inventory_cols)
preventive_df = load_data(PREVENTIVE_FILE, preventive_cols)
corrective_df = load_data(CORRECTIVE_FILE, corrective_cols)
reports_df = load_data(REPORT_HISTORY_FILE, report_cols)

# Default Admin Setup
if users_df.empty or "admin" not in users_df["Username"].values:
    default_admin = pd.DataFrame([[
        "System Administrator", "Engineering Exec", "System Management", "System Admin (Full Control)", "admin", hash_password("Admin@123"), datetime.now().strftime("%Y-%m-%d")
    ]], columns=user_cols)
    users_df = pd.concat([users_df, default_admin], ignore_index=True)
    save_data(users_df, USER_FILE)

# Priority & Status Processing Engine
def process_and_sort_plans(df):
    if df.empty:
        return df
    df["Progress (%)"] = pd.to_numeric(df["Progress (%)"], errors='coerce').fillna(0).astype(int)
    df["Budget (ETB)"] = pd.to_numeric(df["Budget (ETB)"], errors='coerce').fillna(0.0)
    priority_weights = {"🔴 High / Emergency": 3, "🟡 Medium": 2, "🟢 Low": 1}
    df["Priority_Score"] = df["Priority Level"].map(priority_weights).fillna(1)
    df["Temp_End_Date"] = pd.to_datetime(df["End Date"], errors='coerce')
    df = df.sort_values(by=["Status", "Priority_Score", "Temp_End_Date"], ascending=[True, False, True]).drop(columns=["Priority_Score", "Temp_End_Date"])
    return df

plan_df = process_and_sort_plans(plan_df)

# ---------------------------------------------------------
# AUTHENTICATION & SESSION MANAGEMENT
# ---------------------------------------------------------
if 'logged_in' not in st.session_state:
    st.session_state.logged_in = False
    st.session_state.user_info = None
if 'failed_attempts' not in st.session_state:
    st.session_state.failed_attempts = 0
if 'form_key_suffix' not in st.session_state:
    st.session_state.form_key_suffix = 0
if 'active_tab' not in st.session_state:
    st.session_state.active_tab = "📊 Dashboard"

def reset_form_inputs():
    st.session_state.form_key_suffix += 1

def login():
    st.title("🔐 Enterprise Portal v13.0 Login")
    st.caption("🔒 የተጠበቀ የሲስተም መግቢያ ገጽ - ህጋዊ የመግቢያ መረጃዎን ያስገቡ")
    
    users_df = load_data(USER_FILE, user_cols)
    
    col1, col2, col3 = st.columns([1, 2, 1])
    with col2:
        if st.session_state.failed_attempts >= 5:
            st.error("⛔ በተደጋጋሚ የተሳሳተ የይለፍ ቃል በመሞከርዎ አካውንቱ ተቆልፏል! ገጹን Refresh አድርገው ይሞክሩ።")
            st.stop()

        input_user = sanitize_input(st.text_input("Username:"))
        input_pass = st.text_input("Password:", type="password")

        if st.button("ወደ ሲስተሙ ግባ (Login)", use_container_width=True):
            input_user_clean = input_user.strip()
            input_pass_clean = input_pass.strip()
            
            salted_hash = hash_password(input_pass_clean)
            plain_hash = hashlib.sha256(input_pass_clean.encode('utf-8')).hexdigest()

            # Multi-credential validation
            user_match = users_df[
                (users_df["Username"].astype(str).str.strip() == input_user_clean) & 
                (
                    (users_df["Password"].astype(str).str.strip() == salted_hash) | 
                    (users_df["Password"].astype(str).str.strip() == plain_hash) | 
                    (users_df["Password"].astype(str).str.strip() == input_pass_clean)
                )
            ]

            if user_match.empty and input_user_clean == "admin" and input_pass_clean in ["Admin@123", "Admin@1234"]:
                admin_row = users_df[users_df["Username"] == "admin"]
                if not admin_row.empty:
                    user_match = admin_row

            if not user_match.empty:
                st.session_state.logged_in = True
                st.session_state.user_info = user_match.iloc[0].to_dict()
                st.session_state.failed_attempts = 0
                st.success(f"እንኳን በደህና መጡ {st.session_state.user_info.get('Full Name', 'Admin')}!")
                st.rerun()
            else:
                st.session_state.failed_attempts += 1
                st.error("የተሳሳተ Username ወይም Password!")

if not st.session_state.logged_in:
    login()
    st.stop()

user = st.session_state.user_info
role = user.get("Role Privilege", "Viewer")

# ---------------------------------------------------------
# NAVIGATION & HEADER
# ---------------------------------------------------------
st.markdown("<div class='top-bar-title'><h2>🏗️ FEDERAL TVET CMMS & ENTERPRISE MANAGEMENT SYSTEM v13.0</h2></div>", unsafe_allow_html=True)

tab_names = [
    "📊 Dashboard", 
    "🛠️ Maintenance", 
    "📅 Preventive", 
    "🏷️ Assets & QR", 
    "📊 Projects", 
    "📦 Inventory", 
    "📈 Reports", 
    "👥 Users", 
    "⚙️ Settings"
]

cols = st.columns(len(tab_names))
for i, tab in enumerate(tab_names):
    btn_type = "primary" if st.session_state.active_tab == tab else "secondary"
    if cols[i].button(tab, key=f"top_tab_{i}", type=btn_type, use_container_width=True):
        st.session_state.active_tab = tab
        st.rerun()

st.markdown("---")

# SIDEBAR CONTROLS
st.sidebar.title(f"👤 {user.get('Full Name', 'User')}")
st.sidebar.info(f"**ክፍል:** {user.get('Department', 'N/A')}\n\n**ስልጣን:** {role}")
if st.sidebar.button("🚪 ውጣ (Logout)", use_container_width=True):
    st.session_state.logged_in = False
    st.session_state.user_info = None
    st.rerun()

st.sidebar.markdown("---")

active = st.session_state.active_tab

# ---------------------------------------------------------
# MODULE IMPLEMENTATIONS
# ---------------------------------------------------------

# --- 1. DASHBOARD ---
if active == "📊 Dashboard":
    st.sidebar.markdown("### 📊 Dashboard Sub-Menu")
    sub_dash = st.sidebar.radio("ምረጥ:", ["የአጠቃላይ ሁኔታ (Overview)", "የጥገና አፈፃፀም", "ፈጣን KPIs"])
    
    st.title("📊 Executive Dashboard")
    
    if sub_dash == "የአጠቃላይ ሁኔታ (Overview)":
        k1, k2, k3, k4, k5, k6 = st.columns(6)
        tot_plans = len(plan_df)
        comp_plans = len(plan_df[plan_df["Status"] == "Completed"]) if not plan_df.empty else 0
        prog_plans = len(plan_df[plan_df["Status"] == "In Progress"]) if not plan_df.empty else 0
        tot_budget = plan_df["Budget (ETB)"].sum() if not plan_df.empty else 0
        avg_prog = plan_df["Progress (%)"].mean() if not plan_df.empty else 0
        tot_assets = len(assets_df)

        k1.metric("ጠቅላላ ፕሮጀክቶች", tot_plans)
        k2.metric("የተጠናቀቁ", comp_plans)
        k3.metric("በሂደት ላይ ያሉ", prog_plans)
        k4.metric("አማካይ አፈፃፀም", f"{avg_prog:.1f}%")
        k5.metric("ጠቅላላ በጀት", f"{tot_budget:,.0f} ETB")
        k6.metric("የተመዘገቡ ንብረቶች", tot_assets)

        st.markdown("---")
        col_a, col_b = st.columns(2)
        with col_a:
            st.subheader("📌 በስራ ዘርፍ እና አይነት የተሰሩ ስራዎች")
            if not plan_df.empty:
                fig1 = px.histogram(plan_df, x="Department", color="Work Category", barmode="group", text_auto=True, color_discrete_sequence=px.colors.qualitative.Set2)
                st.plotly_chart(fig1, use_container_width=True)
        with col_b:
            st.subheader("💰 የበጀት ክፍፍል በየጊዜ ክፍተቱ (Quarter)")
            if not plan_df.empty:
                fig2 = px.pie(plan_df, names="Quarter", values="Budget (ETB)", hole=0.4, color_discrete_sequence=px.colors.qualitative.Pastel)
                st.plotly_chart(fig2, use_container_width=True)

    elif sub_dash == "የጥገና አፈፃፀም":
        st.subheader("🛠️ የጥገና ስራዎች እና የመሳሪያዎች ሁኔታ")
        st.dataframe(corrective_df, use_container_width=True)

    elif sub_dash == "ፈጣን KPIs":
        st.subheader("⚡ ፈጣን የስራ አፈፃፀም መላኪያዎች (KPIs)")
        c1, c2, c3 = st.columns(3)
        c1.metric("የተጠናቀቁ ጥገናዎች", len(corrective_df[corrective_df["Status"]=="Completed"]) if not corrective_df.empty else 0)
        c2.metric("ክፍት የጥገና ጥያቄዎች", len(corrective_df[corrective_df["Status"]=="Open"]) if not corrective_df.empty else 0)
        c3.metric("ያለቁ የመጋዘን እቃዎች", len(inventory_df[pd.to_numeric(inventory_df["Quantity In Stock"], errors='coerce').fillna(0) <= pd.to_numeric(inventory_df["Min Reorder Level"], errors='coerce').fillna(0)]) if not inventory_df.empty else 0)

# --- 2. MAINTENANCE ---
elif active == "🛠️ Maintenance":
    st.sidebar.markdown("### 🛠️ Maintenance Sub-Menu")
    sub_maint = st.sidebar.radio("ምረጥ:", ["የጥገና ጥያቄዎች (Requests)", "አዲስ የጥገና ጥያቄ"])
    
    st.title("🛠️ Maintenance CMMS - የጥገና ስራዎች")
    
    if sub_maint == "የጥገና ጥያቄዎች (Requests)":
        st.subheader("📋 የጥገና ጥያቄዎች ዝርዝር")
        st.dataframe(corrective_df, use_container_width=True)
    elif sub_maint == "አዲስ የጥገና ጥያቄ":
        k = st.session_state.form_key_suffix
        with st.form(f"corrective_form_{k}"):
            st.subheader("📝 አዲስ የስብራት/የጥገና ጥያቄ አስገባ")
            c1, c2 = st.columns(2)
            with c1:
                asset_loc = sanitize_input(st.text_input("የንብረቱ/ቦታው መግለጫ*", key=f"c_loc_{k}"))
                rep_by = sanitize_input(st.text_input("ሪፖርት ያደረገው ሰው/ክፍል*", key=f"c_rep_{k}"))
                priority = st.selectbox("የአስቸኳይነት ደረጃ*", ["🔴 Emergency", "🟡 High", "🟢 Normal"], key=f"c_prio_{k}")
            with c2:
                tech = sanitize_input(st.text_input("የተመደበው ባለሙያ/ቡድን*", key=f"c_tech_{k}"))
                desc = sanitize_input(st.text_area("የብልሽቱ አይነት መግለጫ*", key=f"c_desc_{k}"))
            
            if st.form_submit_button("💾 ጥያቄውን መዝግብ"):
                if asset_loc and desc:
                    w_id = f"WO-{len(corrective_df) + 101}"
                    new_row = pd.DataFrame([[
                        w_id, asset_loc, desc, rep_by, datetime.now().strftime("%Y-%m-%d"), priority, tech, "Open"
                    ]], columns=corrective_cols)
                    corrective_df = pd.concat([corrective_df, new_row], ignore_index=True)
                    save_data(corrective_df, CORRECTIVE_FILE)
                    st.success(f"✅ የጥገና ጥያቄው ተመዝግቧል! Work Order ID: `{w_id}`")
                    reset_form_inputs()
                    st.rerun()

# --- 3. PREVENTIVE MAINTENANCE ---
elif active == "📅 Preventive":
    st.sidebar.markdown("### 📅 Preventive Sub-Menu")
    sub_prev = st.sidebar.radio("ምረጥ:", ["የጥገና መርሃ-ግብር (Schedules)", "አዲስ መርሃግብር ጨምር"])
    
    st.title("📅 Preventive Maintenance (የቅድመ-መከላከል ጥገና)")
    
    if sub_prev == "የጥገና መርሃ-ግብር (Schedules)":
        st.subheader("📋 የቅድመ-መከላከል ጥገና መርሃግብሮች")
        st.dataframe(preventive_df, use_container_width=True)
    elif sub_prev == "አዲስ መርሃግብር ጨምር":
        k = st.session_state.form_key_suffix
        with st.form(f"pm_form_{k}"):
            st.subheader("➕ አዲስ የቅድመ-መከላከል መርሃግብር መመዝገቢያ")
            c1, c2 = st.columns(2)
            with c1:
                pm_asset = sanitize_input(st.text_input("የንብረቱ ID ወይም አርእስት*", key=f"pm_ast_{k}"))
                freq = st.selectbox("የጥገና ድግግሞሽ*", ["Weekly", "Monthly", "Quarterly", "Annual"], key=f"pm_freq_{k}")
            with c2:
                tech = sanitize_input(st.text_input("ኃላፊ ባለሙያ*", key=f"pm_tech_{k}"))
                next_d = st.date_input("ቀጣይ የጥገና ቀን*", value=date.today(), key=f"pm_next_{k}")
                
            if st.form_submit_button("💾 መርሃግብር መዝግብ"):
                if pm_asset:
                    pm_id = f"PM-{len(preventive_df) + 101}"
                    new_row = pd.DataFrame([[
                        pm_id, pm_asset, freq, tech, datetime.now().strftime("%Y-%m-%d"), str(next_d), "Scheduled"
                    ]], columns=preventive_cols)
                    preventive_df = pd.concat([preventive_df, new_row], ignore_index=True)
                    save_data(preventive_df, PREVENTIVE_FILE)
                    st.success(f"✅ የቅድመ-መከላከል መርሃግብር ተመዝግቧል! PM ID: `{pm_id}`")
                    reset_form_inputs()
                    st.rerun()

# --- 4. ASSETS & QR ---
elif active == "🏷️ Assets & QR":
    st.sidebar.markdown("### 🏷️ Assets Sub-Menu")
    sub_asset = st.sidebar.radio("ምረጥ:", ["የተመዘገቡ ንብረቶች መዝገብ", "አዲስ ንብረት መመዝገቢያ"])
    
    st.title("🏷️ Asset Register & QR Code")
    
    if sub_asset == "የተመዘገቡ ንብረቶች መዝገብ":
        st.subheader("📋 የተመዘገቡ ንብረቶች መዝገብ")
        st.dataframe(assets_df, use_container_width=True)
    elif sub_asset == "አዲስ ንብረት መመዝገቢያ":
        k = st.session_state.form_key_suffix
        with st.form(f"asset_form_{k}"):
            st.subheader("➕ አዲስ ንብረት መዝግብ")
            c1, c2 = st.columns(2)
            with c1:
                a_name = sanitize_input(st.text_input("የንብረቱ ስም*", key=f"a_name_{k}"))
                a_cat = st.selectbox("ምድብ*", ["Machinery", "Vehicle", "Electrical Unit", "Sanitary Infrastructure", "IT Equipment"], key=f"a_cat_{k}")
                a_dept = st.selectbox("የስራ ክፍል*", ["Construction", "Electrical", "Sanitary", "IT/Admin"], key=f"a_dept_{k}")
                a_cost = st.number_input("የተገዛበት ዋጋ (ETB)*", min_value=0.0, step=1000.0, key=f"a_cost_{k}")
            with c2:
                a_loc = sanitize_input(st.text_input("የሚገኝበት ቦታ/ህንፃ*", key=f"a_loc_{k}"))
                a_pdate = st.date_input("የተገዛበት ቀን*", value=date.today(), key=f"a_pdate_{k}")
                a_cond = st.selectbox("የአሁን ሁኔታ*", ["Excellent", "Good", "Needs Maintenance", "Critical"], key=f"a_cond_{k}")
                
            if st.form_submit_button("💾 ንብረቱን መዝግብ"):
                if a_name and a_loc:
                    ast_id = f"AST-{len(assets_df) + 101}"
                    qr_data = f"ASSET-{ast_id}-{a_name}"
                    new_row = pd.DataFrame([[
                        ast_id, a_name, a_cat, a_dept, a_loc, str(a_pdate), a_cost, a_cond, "Active", qr_data
                    ]], columns=asset_cols)
                    assets_df = pd.concat([assets_df, new_row], ignore_index=True)
                    save_data(assets_df, ASSETS_FILE)
                    st.success(f"✅ ንብረቱ በስኬት ተመዝግቧል! Asset ID: `{ast_id}`")
                    reset_form_inputs()
                    st.rerun()

# --- 5. PROJECTS ---
elif active == "📊 Projects":
    st.sidebar.markdown("### 📊 Project Sub-Menu")
    sub_proj = st.sidebar.radio("ምረጥ:", ["የስራዎች መዝገብና ኤዲት ማድረጊያ", "አዲስ ስራ መመዝገቢያ", "የፕሮግረስ ማዘመኛ"])
    
    st.title("📊 Project Management")
    
    if sub_proj == "የስራዎች መዝገብና ኤዲት ማድረጊያ":
        st.subheader("📋 ሁሉም የተመዘገቡ ስራዎች")
        st.dataframe(plan_df, use_container_width=True)
    elif sub_proj == "አዲስ ስራ መመዝገቢያ":
        k = st.session_state.form_key_suffix
        with st.form(f"manual_task_form_{k}"):
            st.subheader("📝 አዲስ ስራ መመዝገቢያ")
            c1, c2 = st.columns(2)
            with c1:
                t_dept = st.selectbox("የስራ ዘርፍ", ["Construction", "Electrical", "Sanitary"], key=f"t_dept_{k}")
                t_cat = st.selectbox("የስራ አይነት", ["New Project", "Maintenance"], key=f"t_cat_{k}")
                t_title = sanitize_input(st.text_input("የስራው መግለጫ / አርእስት*", key=f"t_title_{k}"))
                t_loc = sanitize_input(st.text_input("የሚሰራበት ቦታ / ህንፃ*", key=f"t_loc_{k}"))
                t_mode = st.selectbox("የአሰራር ሁኔታ*", ["In-House (በውስጥ አቅም)", "Outsourced / Contract (በጨረታ)"], key=f"t_mode_{k}")
                t_team = sanitize_input(st.text_input("ኃላፊነት የተሰጠው ቡድን/ባለሙያ*", key=f"t_team_{k}"))
            
            with c2:
                t_qtr = st.selectbox("Quarter", ["Q1", "Q2", "Q3", "Q4"], key=f"t_qtr_{k}")
                t_start = st.date_input("Start Date", value=date.today(), key=f"t_start_{k}")
                t_end = st.date_input("End Date", value=date.today(), key=f"t_end_{k}")
                t_prio = st.selectbox("የአስቸኳይነት ደረጃ*", ["🔴 High / Emergency", "🟡 Medium", "🟢 Low"], key=f"t_prio_{k}")
                t_budget = st.number_input("የተመደበ በጀት (ETB)", min_value=0.0, step=1000.0, key=f"t_budget_{k}")

            c_name = sanitize_input(st.text_input("የኮንትራክተር ስም (ካለ)", value="N/A", key=f"c_name_{k}"))
            c_ref = sanitize_input(st.text_input("የውል ስምምነት ቁጥር (ካለ)", value="N/A", key=f"c_ref_{k}"))
            c_terms = sanitize_input(st.text_area("የውል አስፈላጊ ሁኔታዎች", value="N/A", key=f"c_terms_{k}"))

            if st.form_submit_button("💾 ስራውን መዝግብ"):
                if t_title and t_loc:
                    new_id = f"PLAN-{len(plan_df) + 101}"
                    new_task_row = pd.DataFrame([[
                        new_id, t_dept, t_cat, t_title, t_loc, t_qtr, 
                        t_mode, c_name, c_ref, c_terms,
                        str(t_start), str(t_end), t_prio, t_team, t_budget, 0, "Open"
                    ]], columns=plan_cols)
                    
                    plan_df = pd.concat([plan_df, new_task_row], ignore_index=True)
                    plan_df = process_and_sort_plans(plan_df)
                    save_data(plan_df, ANNUAL_PLAN_FILE)
                    st.success(f"✅ ስራው በስኬት ተመዝግቧል! ID: `{new_id}`")
                    reset_form_inputs()
                    st.rerun()
    elif sub_proj == "የፕሮግረስ ማዘመኛ":
        st.subheader("🛠️ የሥራ ፕሮግረስ ማስተካከያ")
        if not plan_df.empty:
            sel_p = st.selectbox("የሚሰሩትን ስራ ይምረጡ:", plan_df["Plan ID"].dropna().tolist(), key="p_sel_quick")
            p_data = plan_df[plan_df["Plan ID"] == sel_p].iloc[0]
            curr_prog = int(p_data.get("Progress (%)", 0))
            new_p = st.slider("አዲሱን የሥራ ፕሮግረስ (%) ይምረጡ:", min_value=0, max_value=100, value=curr_prog)
            
            auto_st = "Open" if new_p == 0 else ("In Progress" if new_p < 100 else "Completed")
            if st.button("ፕሮግረስ አዘምን"):
                plan_df.loc[plan_df["Plan ID"] == sel_p, "Progress (%)"] = new_p
                plan_df.loc[plan_df["Plan ID"] == sel_p, "Status"] = auto_st
                plan_df = process_and_sort_plans(plan_df)
                save_data(plan_df, ANNUAL_PLAN_FILE)
                st.success("✅ ፕሮግረሱ ተዘምኗል!")
                st.rerun()

# --- 6. INVENTORY ---
elif active == "📦 Inventory":
    st.sidebar.markdown("### 📦 Inventory Sub-Menu")
    sub_inv = st.sidebar.radio("ምረጥ:", ["የመጋዘን እቃዎች መዝገብ", "አዲስ እቃ መመዝገቢያ"])
    
    st.title("📦 Inventory Management - የእቃና መለዋወጫ መጋዘን")
    
    if not inventory_df.empty:
        inventory_df["Quantity In Stock"] = pd.to_numeric(inventory_df["Quantity In Stock"], errors="coerce").fillna(0)
        inventory_df["Unit Cost (ETB)"] = pd.to_numeric(inventory_df["Unit Cost (ETB)"], errors="coerce").fillna(0)
        inventory_df["Total Value (ETB)"] = inventory_df["Quantity In Stock"] * inventory_df["Unit Cost (ETB)"]

    if sub_inv == "የመጋዘን እቃዎች መዝገብ":
        st.subheader("📋 የመጋዘን እቃዎች መዝገብ")
        st.dataframe(inventory_df, use_container_width=True)
        tot_inv_val = inventory_df["Total Value (ETB)"].sum() if not inventory_df.empty else 0
        st.metric("💰 ጠቅላላ የመጋዘን እቃዎች ዋጋ:", f"{tot_inv_val:,.2f} ETB")

    elif sub_inv == "አዲስ እቃ መመዝገቢያ":
        k = st.session_state.form_key_suffix
        with st.form(f"inv_form_{k}"):
            st.subheader("➕ አዲስ የመጋዘን እቃ መዝግብ")
            c1, c2 = st.columns(2)
            with c1:
                i_name = sanitize_input(st.text_input("የእቃው ስም*", key=f"i_name_{k}"))
                i_cat = st.selectbox("ምድብ*", ["Electrical Spare", "Sanitary Fitting", "Civil Material", "Tools"], key=f"i_cat_{k}")
                i_qty = st.number_input("ብዛት (Quantity)*", min_value=0, value=10, key=f"i_qty_{k}")
            with c2:
                i_min = st.number_input("አነስተኛ የማሳወቂያ መጠን (Min Reorder Level)*", min_value=0, value=5, key=f"i_min_{k}")
                i_cost = st.number_input("የአንዱ ዋጋ (Unit Cost ETB)*", min_value=0.0, step=10.0, key=f"i_cost_{k}")
                i_bin = sanitize_input(st.text_input("የተቀመጠበት ቦታ/Bin*", key=f"i_bin_{k}"))

            if st.form_submit_button("💾 እቃውን መዝግብ"):
                if i_name:
                    item_code = f"SKU-{len(inventory_df) + 101}"
                    tot_val = i_qty * i_cost
                    new_row = pd.DataFrame([[
                        item_code, i_name, i_cat, i_qty, i_min, i_cost, tot_val, i_bin
                    ]], columns=inventory_cols)
                    inventory_df = pd.concat([inventory_df, new_row], ignore_index=True)
                    save_data(inventory_df, INVENTORY_FILE)
                    st.success(f"✅ እቃው በስኬት ተመዝግቧል! Item Code: `{item_code}`")
                    reset_form_inputs()
                    st.rerun()

# --- 7. REPORTS ---
elif active == "📈 Reports":
    st.sidebar.markdown("### 📈 Reports Sub-Menu")
    sub_rep = st.sidebar.radio("ምረጥ:", ["የላቀ ሪፖርቶች ማውጫ", "የተሰሩ ሪፖርቶች ታሪክ (Report History)"])
    
    st.title("📈 Reports & Analytics (የተሟላ ሪፖርት ማውጫ)")
    
    if sub_rep == "የላቀ ሪፖርቶች ማውጫ":
        st.subheader("🎯 የሚፈልጉትን የሪፖርት መስፈርት ይምረጡ")
        
        r_col1, r_col2, r_col3 = st.columns(3)
        with r_col1:
            time_frame = st.selectbox(
                "📅 የጊዜ ክፍተት (Timeframe):", 
                ["የሳምንት (Weekly)", "የወር (Monthly)", "የእሩብ ዓመት Q1", "የእሩብ ዓመት Q2", "የእሩብ ዓመት Q3", "የእሩብ ዓመት Q4", "የግማሽ ዓመት (6-Month)", "የ9 ወር (9-Month)", "የዓመት (Annual / All)"]
            )
        with r_col2:
            dept_filter = st.selectbox(
                "🏢 የሥራ ክፍል (Department):", 
                ["ሁሁሉም ክፍሎች (All)", "Construction", "Electrical", "Sanitary", "IT / Executive"]
            )
        with r_col3:
            module_filter = st.selectbox(
                "🛠️ የሪፖርት አይነት (Module):", 
                ["የፕሮጀክት ስራዎች (Projects Plan)", "የጥገና ስራዎች (Maintenance Work Orders)", "የቅድመ-መከላከል ጥገና (Preventive)", "የንብረት መዝገብ (Asset Register)", "የመጋዘን እቃዎች (Inventory)"]
            )
            
        st.markdown("---")
        
        filtered_data = pd.DataFrame()
        
        if module_filter == "የፕሮጀክት ስራዎች (Projects Plan)":
            filtered_data = plan_df.copy()
            if dept_filter != "ሁሁሉም ክፍሎች (All)" and not filtered_data.empty:
                filtered_data = filtered_data[filtered_data["Department"] == dept_filter]
            if "Q1" in time_frame and not filtered_data.empty: filtered_data = filtered_data[filtered_data["Quarter"] == "Q1"]
            elif "Q2" in time_frame and not filtered_data.empty: filtered_data = filtered_data[filtered_data["Quarter"] == "Q2"]
            elif "Q3" in time_frame and not filtered_data.empty: filtered_data = filtered_data[filtered_data["Quarter"] == "Q3"]
            elif "Q4" in time_frame and not filtered_data.empty: filtered_data = filtered_data[filtered_data["Quarter"] == "Q4"]

        elif module_filter == "የጥገና ስራዎች (Maintenance Work Orders)":
            filtered_data = corrective_df.copy()

        elif module_filter == "የቅድመ-መከላከል ጥገና (Preventive)":
            filtered_data = preventive_df.copy()

        elif module_filter == "የንብረት መዝገብ (Asset Register)":
            filtered_data = assets_df.copy()
            if dept_filter != "ሁሁሉም ክፍሎች (All)" and not filtered_data.empty:
                filtered_data = filtered_data[filtered_data["Department"] == dept_filter]

        elif module_filter == "የመጋዘን እቃዎች (Inventory)":
            filtered_data = inventory_df.copy()

        st.subheader(f"📋 የሪፖርት ውጤት ({len(filtered_data)} የተገኙ መረጃዎች)")
        st.dataframe(filtered_data, use_container_width=True)
        
        st.markdown("---")
        save_col1, save_col2 = st.columns(2)
        
        with save_col1:
            report_title = sanitize_input(st.text_input("የሪፖርቱ ስም/አርእስት (Report Title):", value=f"{module_filter} - {time_frame}"))
            if st.button("💾 ሪፖርቱን በሲስተም መዝግብ (Save to History)"):
                rep_id = f"REP-{len(reports_df) + 101}"
                new_rep_row = pd.DataFrame([[
                    rep_id, report_title, time_frame, dept_filter, module_filter, user.get('Full Name', 'Admin'), datetime.now().strftime("%Y-%m-%d %H:%M"), len(filtered_data)
                ]], columns=report_cols)
                reports_df = pd.concat([reports_df, new_rep_row], ignore_index=True)
                save_data(reports_df, REPORT_HISTORY_FILE)
                st.success(f"✅ ሪፖርቱ በስኬት ተመዝግቧል! Report ID: `{rep_id}`")

        with save_col2:
            st.write("📥 **ሪፖርቱን አውርድ (Export)**")
            if not filtered_data.empty:
                st.download_button(
                    label="📥 በ CSV / Excel ፋይል አውርድ",
                    data=filtered_data.to_csv(index=False).encode('utf-8'),
                    file_name=f"TVET_Report_{datetime.now().strftime('%Y%m%d_%H%M')}.csv",
                    mime="text/csv",
                    use_container_width=True
                )

    elif sub_rep == "የተሰሩ ሪፖርቶች ታሪክ (Report History)":
        st.subheader("📜 ቀደም ሲል ተዘጋጅተው የተመዘገቡ ሪፖርቶች")
        st.dataframe(reports_df, use_container_width=True)

# --- 8. USERS ---
elif active == "👥 Users":
    st.sidebar.markdown("### 👥 User Sub-Menu")
    sub_user = st.sidebar.radio("ምረጥ:", ["የእኔ አካውንትና የይለፍ ቃል", "አዲስ ተጠቃሚ መመዝገቢያ"])
    
    st.title("👥 User Management (የተጠቃሚዎች አስተዳደር)")
    
    if sub_user == "የእኔ አካውንትና የይለፍ ቃል":
        st.subheader("👤 የእርስዎ መረጃ")
        col_u1, col_u2 = st.columns(2)
        with col_u1:
            st.write(f"**ሙሉ ስም:** {user.get('Full Name', 'Admin')}")
            st.write(f"**የስራ ክፍል:** {user.get('Department', 'N/A')}")
        with col_u2:
            st.write(f"**የተጠቃሚ ስም (Username):** `{user.get('Username', 'admin')}`")
            st.write(f"**የስልጣን ደረጃ:** {role}")
        
        st.markdown("---")
        st.subheader("🔑 የይለፍ ቃል መቀየሪያ (Change Password)")
        
        with st.form("change_pass_form_page"):
            curr_pass = st.text_input("የአሁኑ የይለፍ ቃል*", type="password")
            new_pass = st.text_input("አዲስ የይለፍ ቃል*", type="password")
            confirm_pass = st.text_input("አዲሱን የይለፍ ቃል ድገሙት*", type="password")
            
            if st.form_submit_button("🔄 የይለፍ ቃሌን ቀይር"):
                hashed_curr_pass = hash_password(curr_pass.strip())
                if user.get("Password") != hashed_curr_pass and user.get("Password") != curr_pass.strip():
                    st.error("⛔ ያስገቡት የአሁኑ የይለፍ ቃል የተሳሳተ ነው!")
                elif new_pass != confirm_pass:
                    st.error("⛔ አዲሱ የይለፍ ቃል እና የማረጋገጫ የይለፍ ቃሉ አይመሳሰሉም!")
                else:
                    is_valid, msg = validate_password_strength(new_pass)
                    if not is_valid:
                        st.error(f"⛔ የደህንነት ስጋት፦ {msg}")
                    else:
                        hashed_new_pass = hash_password(new_pass)
                        users_df.loc[users_df["Username"] == user["Username"], "Password"] = hashed_new_pass
                        save_data(users_df, USER_FILE)
                        st.session_state.user_info["Password"] = hashed_new_pass
                        st.success("✅ የይለፍ ቃልዎ በስኬት ተቀይሯል!")

    elif sub_user == "አዲስ ተጠቃሚ መመዝገቢያ":
        if "Admin" in role or user.get('Username') == 'admin':
            st.subheader("👥 አዲስ ተጠቃሚ መመዝገቢያ")
            k = st.session_state.form_key_suffix
            with st.form(f"reg_u_form_{k}"):
                f_name = sanitize_input(st.text_input("ሙሉ ስም*", key=f"u_fname_{k}"))
                u_dept = st.selectbox("የሥራ ክፍል*", ["Engineering Exec", "Construction Department", "Electrical Department", "Sanitary Department"], key=f"u_dept_{k}")
                j_title = sanitize_input(st.text_area("የሥራ ድርሻ*", key=f"u_jtitle_{k}"))
                u_role = st.selectbox("የስልጣን ደረጃ*", ["Viewer (ማየት ብቻ የሚችል)", "Editor & Reporter (ኤዲት ማድረግ የሚችል)", "System Admin (Full Control)"], key=f"u_role_{k}")
                u_name = sanitize_input(st.text_input("Username*", key=f"u_uname_{k}"))
                u_pass = st.text_input("Password*", type="password", key=f"u_pass_{k}")
                
                if st.form_submit_button("🔒 ተጠቃሚውን መዝግብ"):
                    is_valid, msg = validate_password_strength(u_pass)
                    if not is_valid:
                        st.error(f"⛔ የደህንነት ስጋት፦ {msg}")
                    elif u_name in users_df["Username"].values:
                        st.error("⛔ ይህ Username ቀደም ሲል ተይዟል!")
                    elif f_name and u_name and u_pass:
                        secure_pass = hash_password(u_pass)
                        new_u = pd.DataFrame([[f_name, u_dept, j_title, u_role, u_name, secure_pass, datetime.now().strftime("%Y-%m-%d")]], columns=user_cols)
                        users_df = pd.concat([users_df, new_u], ignore_index=True)
                        save_data(users_df, USER_FILE)
                        st.success(f"✅ ተጠቃሚ {f_name} በስኬት ተመዝግቧል!")
                        reset_form_inputs()
                        st.rerun()
            st.markdown("---")
            st.subheader("📋 የተመዘገቡ ተጠቃሚዎች ዝርዝር")
            st.dataframe(users_df.drop(columns=["Password"]), use_container_width=True)
        else:
            st.warning("⛔ አዲስ ተጠቃሚ ለመመዝገብ የ Admin ስልጣን ያስፈልጋል።")

# --- 9. SETTINGS ---
elif active == "⚙️ Settings":
    st.sidebar.markdown("### ⚙️ Settings Sub-Menu")
    sub_set = st.sidebar.radio("ምረጥ:", ["የሲስተም ቅንብሮች እና Backup"])
    
    st.title("⚙️ Settings & System Backup")
    st.success("✅ የ Federal TVET Enterprise Portal v13.0 ሲስተም በጥሩ ሁኔታ በመስራት ላይ ይገኛል።")